# Generated by Django 6.0.6 on 2026-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='user_name',
            field=models.CharField(default='Narayana', max_length=100),
            preserve_default=False,
        ),
    ]
