# Generated by Django 6.0.6 on 2026-06-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_booking_user_booking_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='show_time',
            field=models.CharField(max_length=20),
        ),
    ]
